# -*- coding: utf-8 -*-
"""preprocess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g9q_6E6cj_JJpQ97zBQvRH2NP0_SxzDu
"""

def getfile():
 import pandas as pd

 from google.colab import files
 filename = input('Enter the file name: ')
 files.upload()
 df = pd.read_excel(filename)
 #ARIMA2013_2015SCC.xlsx'
 return df